[build]
  publish = "public"
  functions = "functions"
  command = "npm ci && npm run build"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "14"  # Ajusta esto a la versión de Node.js que estés usando
